base: &DEFAULT
  build: ./web
  volumes:
    - ./web:/usr/src/app
    - ./home:/root/.local
  command:
    "pip install --allow-external --no-cache-dir -i http://pypi.douban.com/simple/ --trusted-host=pypi.douban.com -r requirements.txt --user"

web:
  <<: *DEFAULT  # "inherit" from the configuration above
  restart: always
  expose:
    - "8000"
  volumes:
    - ./web:/usr/src/app
    - ./home:/root/.local
  environment:
    - APP_MODE=Staging

  command:
    "/root/.local/bin/uwsgi -s 0.0.0.0:8000 --pidfile /tmp/app.pid --wsgi-file /usr/src/app/app.py --callable app --processes 4 --threads 2 --master --harakiri 300"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - /data/logs/nginx:/var/log/nginx
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
