web:
  restart: always
  build: ./web
  expose:
    - "8000"
  volumes:
    - ./web:/usr/src/app
  environment:
    - APP_MODE=Staging

  command:
    uwsgi -s 0.0.0.0:8000 --pidfile /tmp/app.pid --wsgi-file /usr/src/app/app.py --callable app --processes 4 --threads 2 --master --harakiri 300

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /data/logs/nginx:/var/log/nginx
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
