base: &DEFAULT
  build: ./web
  volumes:
    - ./web:/usr/src/app
    - ./home:/root/.local
  command:
    "pip install --no-cache-dir -i https://pypi.mirrors.ustc.edu.cn/simple/ -r requirements.txt --user"

web:
  <<: *DEFAULT  # "inherit" from the configuration above
  restart: always
  expose:
    - "8000"
  volumes:
    - ./web:/usr/src/app
    - ./home:/root/.local
    - /data/logs/supervisor:/logs
  environment:
    - APP_MODE=Staging

  command:
    "/root/.local/bin/supervisord -c /usr/src/app/supervisor.conf"
    
nginx:
  restart: always
  build: ./nginx/
  ports:
    - "8080:80"
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - /data/logs/nginx:/var/log/nginx
  links:
    - web:web
